#!/usr/bin/env python3
"""
This module provides a function that creates and returns
an asyncio Task for the wait_random coroutine.
"""

import asyncio

wait_random = __import__('0-basic_async_syntax').wait_random


def task_wait_random(max_delay: int) -> asyncio.Task:
    """
    Creates an asyncio Task that executes the wait_random coroutine.

    The task is scheduled to run concurrently within the event loop
    and will wait for a random delay up to the specified maximum value.

    Args:
        max_delay (int): The maximum delay in seconds that can be
            generated by the wait_random coroutine.

    Returns:
        asyncio.Task: A task object wrapping the wait_random coroutine.
    """
    return asyncio.create_task(wait_random(max_delay))
